### PR TITLE
Fixes #21: encoding support for Python 2

### LINKED ISSUE #21: Defaulting to 'utf-8' encoding breaks pymlconf on Python 2
Python 2 does not have support for open() with encoding='utf-8. I'm using a package with depends on pymlconf on Python 2 and this change has broken my tests. Let me know if you need any more information to debug this.

```
.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:76: in __init__
    self.load_files(files)
.tox/py27/lib/python2.7/site-packages/pymlconf/config_manager.py:109: in load_files
    loaded_yaml = load_yaml(f, self.context, encoding=self.encoding)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/home/ubuntu/<SNIP>'
macros = {}, encoding = 'utf-8'

    def load_yaml(file_path, macros=None, encoding='utf-8'):
>       stream = open(file_path, encoding=encoding)
E       TypeError: 'encoding' is an invalid keyword argument for this function

.tox/py27/lib/python2.7/site-packages/pymlconf/yaml_helper.py:29: TypeError
```

### PR DESCRIPTION
**Pull request by Sharez**

### CODE REVIEW

**Comment by DonnchaC** [comment]
I haven't had a chance to test this, but that solution looks reasonable to me. Thanks for getting this fixed quickly!

**Comment by DonnchaC** [comment]
I'd recommend using tox to automatically run your tests in Python 2 and Python 3 environments.

**Comment by pylover** [comment]
Thanks a lot @Sharez

**Comment by pylover** [comment]
@DonnchaC, thanks for suggestion.

**Pull request merged**
